#-------------------------------------------------
#
# Project created by QtCreator 2016-10-22T14:47:35
#
#-------------------------------------------------

QT       += core gui network multimedia
CONFIG   += c++11

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = Monopoly2D_Game
TEMPLATE = app

DESTDIR     = bin # Target file directory
OBJECTS_DIR = generated_files # Intermediate object files directory
MOC_DIR     = generated_files # Intermediate moc files directory

SOURCES += main.cpp\
        core/ui/mainwindow.cpp \
    core/ui/extensions/sidebar.cpp \
    core/game/entity/token.cpp \
    core/game/entity/card.cpp \
    core/game/entity/field.cpp \
    core/applicationloader.cpp \
    core/utils/windowUtils/windowutils.cpp \
    core/utils/constantutils.cpp \
    core/utils/boardUtils/boardutils.cpp \
    core/utils/resourceutils.cpp \
    core/utils/extensionUtils/sidebar/sidebarutils.cpp \
    core/game/entity/fields/propertyfield.cpp \
    core/game/entity/fields/companyfield.cpp \
    core/game/entity/fields/cornerfield.cpp \
    core/game/entity/fields/cardfield.cpp \
    core/game/entity/fields/taxfield.cpp \
    core/game/entity/cards/chancecard.cpp \
    core/game/entity/cards/communitychestcard.cpp \
    core/game/board/board.cpp \
    core/ui/extensions/mainview.cpp \
    core/game/managers/gamemanager.cpp \
    core/game/managers/boardmanager.cpp \
    core/utils/fieldUtils/fieldrotationutils.cpp \
    core/utils/fieldUtils/fieldtranslateutils.cpp \
    core/utils/fieldUtils/fieldgeometryutils.cpp \
    core/utils/boardUtils/boarddisplayutils.cpp \
    core/game/entity/tokens/automobiletoken.cpp \
    core/game/entity/tokens/battleshiptoken.cpp \
    core/game/entity/tokens/scottishterriertoken.cpp \
    core/game/entity/tokens/tophattoken.cpp \
    core/game/entity/tokens/thimbletoken.cpp \
    core/game/entity/tokens/howitzertoken.cpp \
    core/utils/tokenUtils/tokengeometryutils.cpp \
    core/elements/draggablewidget.cpp \
    core/ui/extensions/components/sidebar/controlbuttons.cpp \
    core/elements/buttonelement.cpp \
    core/utils/tokenUtils/tokenanimationutils.cpp \
    core/game/finance/playerfinance.cpp \
    core/game/player/player.cpp \
    core/game/player/localplayer.cpp \
    core/game/player/networkplayer.cpp \
    core/game/player/ai.cpp \
    core/utils/windowUtils/windowdisplayutils.cpp \
    core/utils/ruleUtils/ruleconstantutils.cpp \
    core/utils/playerUtils/playerutils.cpp \
    core/utils/fieldUtils/fieldcopyutils.cpp \
    core/utils/extensionUtils/gameController/gamecontrollerutils.cpp \
    core/ui/extensions/components/sidebar/fielddisplay.cpp \
    core/utils/extensionUtils/sidebar/sidebardisplayutils.cpp \
    core/utils/extensionUtils/fieldDisplay/sidebarfieldutils.cpp \
    core/utils/extensionUtils/playerDisplay/playerdisplayutils.cpp \
    core/utils/extensionUtils/playerDashboard/playerdashboardutils.cpp \
    core/settings/settingswindow.cpp \
    core/utils/settingsUtils/settingswindowutils.cpp \
    core/utils/boardUtils/boardmovementutils.cpp \
    core/utils/fieldUtils/fieldutils.cpp \
    core/game/entity/fields/possessablefield.cpp \
    core/game/action.cpp \
    core/utils/fieldUtils/fieldDisplayUtils/fieldnamedisplayutils.cpp \
    core/utils/fieldUtils/fieldDisplayUtils/fieldcostdisplayutils.cpp \
    core/utils/fieldUtils/fieldDisplayUtils/fieldimagedisplayutils.cpp \
    core/utils/fieldUtils/fieldDisplayUtils/fieldcolordisplayutils.cpp \
    core/utils/fieldUtils/fieldDisplayUtils/fielddisplayutils.cpp \
    core/game/entity/dice.cpp \
    core/game/managers/fieldsmanager.cpp \
    core/game/managers/cardsmanager.cpp \
    core/utils/gameUtils/gameutils.cpp \
    core/game/managers/fieldvisitmanager.cpp \
    core/ui/extensions/components/mainView/home.cpp \
    core/ui/extensions/components/mainView/lobby/lobby.cpp \
    core/ui/extensions/components/mainView/lobby/locallobby.cpp \
    core/ui/extensions/components/mainView/lobby/networklobby.cpp \
    core/settings/settingsmanager.cpp \
    core/utils/tokenUtils/tokenpixmaputils.cpp \
    core/utils/extensionUtils/lobbyUtils/locallobbyutils.cpp \
    core/utils/extensionUtils/lobbyUtils/lobbyutils.cpp \
    core/ui/extensions/components/mainView/lobby/playerslist.cpp \
    core/utils/errorUtils/errorhandler.cpp \
    core/ui/extensions/components/mainView/boardDisplay/boarddisplay.cpp \
    core/elements/textline.cpp \
    core/game/singleplayergame.cpp \
    core/ui/extensions/components/mainView/boardDisplay/dicedisplay.cpp \
    core/ui/extensions/components/sidebar/playerdashboard.cpp \
    core/game/managers/playeractionmanager.cpp \
    core/utils/buildingUtils/buildingutils.cpp \
    core/utils/buildingUtils/buildingdisplayutils.cpp \
    core/ui/extensions/components/sidebar/participantsview.cpp \
    core/utils/fieldUtils/possessablefieldutils.cpp \
    core/utils/fieldUtils/fieldmortgageutils.cpp \
    core/utils/fieldUtils/fieldbuildingutils.cpp \
    core/game/trade/offer.cpp \
    core/game/trade/offerpair.cpp \
    core/game/trade/tradesetup.cpp \
    core/game/trade/playerpicker.cpp \
    network/packets/packet.cpp \
    network/server/server.cpp \
    network/client/client.cpp \
    network/client/serverclient.cpp \
    network/client/localclient.cpp \
    network/packets/connectpacket.cpp \
    network/packets/disconnectpacket.cpp \
    network/packets/errorpacket.cpp \
    network/packets/pingpacket.cpp \
    network/packets/chatpacket.cpp \
    network/packets/serverdownpacket.cpp \
    network/packets/movepacket.cpp \
    network/packets/setturnpacket.cpp \
    network/packets/playeractionpacket.cpp \
    network/packets/requestpaymentpacket.cpp \
    network/packets/updateboardpacket.cpp \
    network/server/serverwidget.cpp \
    network/packets/kickpacket.cpp \
    network/packets/startpacket.cpp \
    network/packets/stoppacket.cpp \
    core/ui/extensions/components/sidebar/chat.cpp \
    core/elements/message.cpp \
    core/ui/extensions/components/mainView/lobby/networklobbyinitializer.cpp \
    core/game/mpgame.cpp \
    core/game/victoryscreen.cpp \
    network/packets/rolldicepacket.cpp \
    network/packets/updatedicepacket.cpp \
    network/packets/endturnpacket.cpp \
    network/packets/tradepacket.cpp \
    network/server/serverchat.cpp \
    network/server/commands/command.cpp \
    network/server/commands/helpcommand.cpp \
    network/server/commands/commandmanager.cpp \
    network/packets/depositpacket.cpp \
    network/packets/withdrawpacket.cpp \
    core/ui/extensions/components/sidebar/mpdashboard.cpp \
    network/server/serverplayeractionmanager.cpp \
    network/packets/jailpacket.cpp \
    network/packets/buypacket.cpp \
    core/elements/notification.cpp \
    core/notifications/notificationmanager.cpp \
    network/packets/updatedashboardpacket.cpp \
    network/packets/notificationpacket.cpp \
    network/packets/updatepingpacket.cpp \
    core/game/trade/tradeview.cpp \
    core/sounds/soundmanager.cpp

HEADERS  += core/ui/mainwindow.h \
    core/ui/extensions/sidebar.h \
    core/game/entity/token.h \
    core/game/entity/card.h \
    core/game/entity/field.h \
    core/applicationloader.h \
    core/utils/windowUtils/windowutils.h \
    core/utils/constantutils.h \
    core/utils/boardUtils/boardutils.h \
    core/utils/resourceutils.h \
    core/utils/extensionUtils/sidebar/sidebarutils.h \
    core/game/entity/fields/propertyfield.h \
    core/game/entity/fields/companyfield.h \
    core/game/entity/fields/cornerfield.h \
    core/game/entity/fields/cardfield.h \
    core/game/entity/fields/taxfield.h \
    core/game/entity/cards/chancecard.h \
    core/game/entity/cards/communitychestcard.h \
    core/game/board/board.h \
    core/ui/extensions/mainview.h \
    core/game/managers/gamemanager.h \
    core/game/managers/boardmanager.h \
    core/utils/fieldUtils/fieldrotationutils.h \
    core/utils/fieldUtils/fieldtranslateutils.h \
    core/utils/fieldUtils/fieldgeometryutils.h \
    core/utils/boardUtils/boarddisplayutils.h \
    core/game/entity/tokens/automobiletoken.h \
    core/game/entity/tokens/battleshiptoken.h \
    core/game/entity/tokens/scottishterriertoken.h \
    core/game/entity/tokens/tophattoken.h \
    core/game/entity/tokens/thimbletoken.h \
    core/game/entity/tokens/howitzertoken.h \
    core/utils/tokenUtils/tokengeometryutils.h \
    core/elements/draggablewidget.h \
    core/ui/extensions/components/sidebar/controlbuttons.h \
    core/elements/buttonelement.h \
    core/utils/tokenUtils/tokenanimationutils.h \
    core/game/finance/playerfinance.h \
    core/game/player/player.h \
    core/game/player/localplayer.h \
    core/game/player/networkplayer.h \
    core/game/player/ai.h \
    core/utils/windowUtils/windowdisplayutils.h \
    core/utils/ruleUtils/ruleconstantutils.h \
    core/utils/playerUtils/playerutils.h \
    core/utils/fieldUtils/fieldcopyutils.h \
    core/utils/extensionUtils/gameController/gamecontrollerutils.h \
    core/ui/extensions/components/sidebar/fielddisplay.h \
    core/utils/extensionUtils/sidebar/sidebardisplayutils.h \
    core/utils/extensionUtils/fieldDisplay/sidebarfieldutils.h \
    core/utils/extensionUtils/playerDisplay/playerdisplayutils.h \
    core/utils/extensionUtils/playerDashboard/playerdashboardutils.h \
    core/settings/settingswindow.h \
    core/utils/settingsUtils/settingswindowutils.h \
    core/utils/boardUtils/boardmovementutils.h \
    core/utils/fieldUtils/fieldutils.h \
    core/game/entity/fields/possessablefield.h \
    core/game/action.h \
    core/utils/fieldUtils/fieldDisplayUtils/fieldnamedisplayutils.h \
    core/utils/fieldUtils/fieldDisplayUtils/fieldcostdisplayutils.h \
    core/utils/fieldUtils/fieldDisplayUtils/fieldimagedisplayutils.h \
    core/utils/fieldUtils/fieldDisplayUtils/fieldcolordisplayutils.h \
    core/utils/fieldUtils/fieldDisplayUtils/fielddisplayutils.h \
    core/game/entity/dice.h \
    core/game/managers/fieldsmanager.h \
    core/game/managers/cardsmanager.h \
    core/utils/gameUtils/gameutils.h \
    core/game/managers/fieldvisitmanager.h \
    core/ui/extensions/components/mainView/home.h \
    core/ui/extensions/components/mainView/lobby/lobby.h \
    core/ui/extensions/components/mainView/lobby/locallobby.h \
    core/ui/extensions/components/mainView/lobby/networklobby.h \
    core/settings/settingsmanager.h \
    core/utils/tokenUtils/tokenpixmaputils.h \
    core/utils/extensionUtils/lobbyUtils/locallobbyutils.h \
    core/utils/extensionUtils/lobbyUtils/lobbyutils.h \
    core/ui/extensions/components/mainView/lobby/playerslist.h \
    core/utils/errorUtils/errorhandler.h \
    core/ui/extensions/components/mainView/boardDisplay/boarddisplay.h \
    core/elements/textline.h \
    core/game/singleplayergame.h \
    core/ui/extensions/components/mainView/boardDisplay/dicedisplay.h \
    core/ui/extensions/components/sidebar/playerdashboard.h \
    core/game/managers/playeractionmanager.h \
    core/utils/buildingUtils/buildingutils.h \
    core/utils/buildingUtils/buildingdisplayutils.h \
    core/ui/extensions/components/sidebar/participantsview.h \
    core/utils/fieldUtils/possessablefieldutils.h \
    core/utils/fieldUtils/fieldmortgageutils.h \
    core/utils/fieldUtils/fieldbuildingutils.h \
    core/game/trade/offer.h \
    core/game/trade/offerpair.h \
    core/game/trade/tradesetup.h \
    core/game/trade/playerpicker.h \
    network/packets/packet.h \
    network/server/server.h \
    network/client/client.h \
    network/network.h \
    network/client/serverclient.h \
    network/client/localclient.h \
    network/packets/connectpacket.h \
    network/packets/disconnectpacket.h \
    network/packets/errorpacket.h \
    network/packets/pingpacket.h \
    network/packets/chatpacket.h \
    network/packets/serverdownpacket.h \
    network/packets/movepacket.h \
    network/packets/setturnpacket.h \
    network/packets/playeractionpacket.h \
    network/packets/requestpaymentpacket.h \
    network/packets/updateboardpacket.h \
    network/server/serverwidget.h \
    network/packets/kickpacket.h \
    network/packets/startpacket.h \
    network/packets/stoppacket.h \
    core/ui/extensions/components/sidebar/chat.h \
    core/elements/message.h \
    core/ui/extensions/components/mainView/lobby/networklobbyinitializer.h \
    core/game/mpgame.h \
    core/game/victoryscreen.h \
    network/packets/rolldicepacket.h \
    network/packets/updatedicepacket.h \
    network/packets/endturnpacket.h \
    network/packets/tradepacket.h \
    network/server/serverchat.h \
    network/server/commands/command.h \
    network/server/commands/helpcommand.h \
    network/server/commands/commandmanager.h \
    network/packets/depositpacket.h \
    network/packets/withdrawpacket.h \
    core/ui/extensions/components/sidebar/mpdashboard.h \
    network/server/serverplayeractionmanager.h \
    network/packets/jailpacket.h \
    network/packets/buypacket.h \
    core/elements/notification.h \
    core/notifications/notificationmanager.h \
    network/packets/updatedashboardpacket.h \
    network/packets/notificationpacket.h \
    network/packets/updatepingpacket.h \
    core/game/trade/tradeview.h \
    core/sounds/soundmanager.h

RESOURCES += \
    resources/style_resources.qrc \
    resources/animation_resources.qrc \
    resources/font_resources.qrc \
    resources/soundresources.qrc \
    resources/image_resources.qrc
